import { Employee, PayrollPeriod, LeaveRecord, UserAccount, AuditLogItem, EmployeeSchedule } from '../types';

export const initialEmployees: Employee[] = [
  {
    id: 'emp-1',
    employeeId: 'CDL-001',
    firstName: 'Ali',
    lastName: 'Hamza',
    displayName: 'Ali Hamza',
    position: 'Global Dispatch / Call Center',
    department: 'Dispatch Operations',
    status: 'Active',
    employmentType: 'Full-Time',
    payType: 'Hourly',
    payRate: 4.00,
    holidayRate: 6.00,
    startDate: '2023-03-15',
    dateOfBirth: '1992-05-14',
    personalPhone: '(441) 555-0101',
    workPhone: '(441) 292-1234 ext 101',
    email: 'ali.hamza@centraldispatch.bm',
    address: '12 Pembroke Way, Hamilton, Bermuda HM 11',
    emergencyContactName: 'Fatima Hamza',
    emergencyContactPhone: '(441) 555-0102',
    emergencyContactRelation: 'Spouse',
    paymentMethod: 'Direct Deposit',
    bankName: 'Butterfield Bank Bermuda',
    bankAccountMasked: '••••••••4892'
  },
  {
    id: 'emp-2',
    employeeId: 'CDL-002',
    firstName: 'Alesia',
    lastName: 'Brangman',
    displayName: 'Alesia Brangman',
    position: 'Dispatch Supervisor',
    department: 'Dispatch Operations',
    status: 'Active',
    employmentType: 'Full-Time',
    payType: 'Hourly',
    payRate: 20.00,
    holidayRate: 30.00,
    startDate: '2021-08-01',
    dateOfBirth: '1988-11-20',
    personalPhone: '(441) 555-0201',
    workPhone: '(441) 292-1234 ext 102',
    email: 'alesia.b@centraldispatch.bm',
    address: '45 South Shore Road, Paget, Bermuda PG 04',
    emergencyContactName: 'Marcus Brangman',
    emergencyContactPhone: '(441) 555-0202',
    emergencyContactRelation: 'Brother',
    paymentMethod: 'Direct Deposit',
    bankName: 'HSBC Bermuda',
    bankAccountMasked: '••••••••1134'
  },
  {
    id: 'emp-3',
    employeeId: 'CDL-003',
    firstName: 'Tyonika',
    middleInitial: 'Ty',
    lastName: 'McGowan',
    displayName: 'Tyonika McGowan (Ty)',
    position: 'Dispatcher',
    department: 'Dispatch Operations',
    status: 'Active',
    employmentType: 'Full-Time',
    payType: 'Hourly',
    payRate: 16.50,
    holidayRate: 24.75,
    startDate: '2022-01-10',
    dateOfBirth: '1995-02-18',
    personalPhone: '(441) 555-0301',
    workPhone: '(441) 292-1234 ext 103',
    email: 'tyonika.mcgowan@centraldispatch.bm',
    address: '8 Middle Road, Warwick, Bermuda WK 02',
    emergencyContactName: 'Sarah McGowan',
    emergencyContactPhone: '(441) 555-0302',
    emergencyContactRelation: 'Mother',
    paymentMethod: 'Direct Deposit',
    bankName: 'Butterfield Bank Bermuda',
    bankAccountMasked: '••••••••7721'
  },
  {
    id: 'emp-4',
    employeeId: 'CDL-004',
    firstName: 'Neli',
    lastName: 'Outerbridge',
    displayName: 'Neli Outerbridge',
    position: 'Owner / Manager / Director',
    department: 'Executive Office',
    status: 'Active',
    employmentType: 'Full-Time',
    payType: 'Salaried',
    payRate: 45.00,
    holidayRate: 67.50,
    startDate: '2018-01-01',
    dateOfBirth: '1980-07-04',
    personalPhone: '(441) 555-0401',
    workPhone: '(441) 292-1234 ext 100',
    email: 'neli.outerbridge@centraldispatch.bm',
    address: '1 Sea Breeze Lane, Devonshire, Bermuda DV 06',
    emergencyContactName: 'David Outerbridge',
    emergencyContactPhone: '(441) 555-0402',
    emergencyContactRelation: 'Spouse',
    paymentMethod: 'Direct Deposit',
    bankName: 'Butterfield Bank Bermuda',
    bankAccountMasked: '••••••••9900'
  },
  {
    id: 'emp-5',
    employeeId: 'CDL-005',
    firstName: 'SSH',
    lastName: 'SSH',
    displayName: 'SSH, SSH',
    position: 'SSH Dispatch / Call Center',
    department: 'Dispatch Operations',
    status: 'Active',
    employmentType: 'Part-Time',
    payType: 'Hourly',
    payRate: 15.00,
    holidayRate: 22.50,
    startDate: '2023-09-01',
    dateOfBirth: '1998-10-12',
    personalPhone: '(441) 555-0501',
    workPhone: '(441) 292-1234 ext 105',
    email: 'ssh.support@centraldispatch.bm',
    address: '3 North Shore Road, St. George\'s, Bermuda GE 01',
    emergencyContactName: 'James Smith',
    emergencyContactPhone: '(441) 555-0502',
    emergencyContactRelation: 'Guardian',
    paymentMethod: 'Check',
    bankName: 'Clarien Bank',
    bankAccountMasked: '••••••••3311'
  }
];

export const initialPayrollPeriods: PayrollPeriod[] = [
  {
    id: 'pay-2026-09-10',
    periodStart: '2026-09-03',
    periodEnd: '2026-09-09',
    payDate: '2026-09-10',
    status: 'Draft',
    totalHours: 0,
    totalGrossPayroll: 0,
    totalDeductions: 0,
    totalNetPayroll: 0,
    createdBy: 'prashant',
    createdAt: '2026-09-10T08:00:00Z',
    items: [
      {
        employeeId: 'CDL-001',
        employeeName: 'Ali Hamza',
        position: 'Global Dispatch / Call Center',
        department: 'Dispatch Operations',
        regularRate: 4.00,
        regularHours: 0,
        regularPay: 0,
        holidayRate: 0,
        holidayHours: 0,
        holidayPay: 0,
        otherPay: 0,
        deductions: 0,
        totalHours: 0,
        grossPay: 0,
        netPay: 0,
        status: 'Ready'
      },
      {
        employeeId: 'CDL-002',
        employeeName: 'Alesia Brangman',
        position: 'Dispatch Supervisor',
        department: 'Dispatch Operations',
        regularRate: 20.00,
        regularHours: 0,
        regularPay: 0,
        holidayRate: 30.00,
        holidayHours: 0,
        holidayPay: 0,
        otherPay: 0,
        deductions: 0,
        totalHours: 0,
        grossPay: 0,
        netPay: 0,
        status: 'Ready'
      }
    ]
  },
  {
    id: 'pay-2026-09-03',
    periodStart: '2026-08-27',
    periodEnd: '2026-09-02',
    payDate: '2026-09-03',
    status: 'Paid',
    totalHours: 842.50,
    totalGrossPayroll: 28450.00,
    totalDeductions: 530.00,
    totalNetPayroll: 27920.00,
    createdBy: 'prashant',
    createdAt: '2026-09-03T08:00:00Z',
    approvedBy: 'Neli Outerbridge',
    approvedAt: '2026-09-03T14:30:00Z',
    paidAt: '2026-09-03T16:00:00Z',
    items: [
      {
        employeeId: 'CDL-001',
        employeeName: 'Ali Hamza',
        position: 'Global Dispatch / Call Center',
        department: 'Dispatch Operations',
        regularRate: 4.00,
        regularHours: 40,
        regularPay: 160.00,
        holidayRate: 6.00,
        holidayHours: 8,
        holidayPay: 48.00,
        otherPay: 0,
        deductions: 0,
        totalHours: 48,
        grossPay: 208.00,
        netPay: 208.00,
        status: 'Paid'
      },
      {
        employeeId: 'CDL-002',
        employeeName: 'Alesia Brangman',
        position: 'Dispatch Supervisor',
        department: 'Dispatch Operations',
        regularRate: 20.00,
        regularHours: 40,
        regularPay: 800.00,
        holidayRate: 30.00,
        holidayHours: 8,
        holidayPay: 240.00,
        otherPay: 50.00,
        deductions: 25.00,
        totalHours: 48,
        grossPay: 1090.00,
        netPay: 1065.00,
        status: 'Paid'
      }
    ]
  }
];

export const initialLeaves: LeaveRecord[] = [
  {
    id: 'leave-1',
    employeeId: 'CDL-001',
    employeeName: 'Ali Hamza',
    leaveType: 'Vacation',
    startDate: '2026-09-15',
    endDate: '2026-09-20',
    daysCount: 5,
    status: 'Approved',
    notes: 'Annual family leave'
  },
  {
    id: 'leave-2',
    employeeId: 'CDL-003',
    employeeName: 'Tyonika McGowan (Ty)',
    leaveType: 'Sick',
    startDate: '2026-09-08',
    endDate: '2026-09-09',
    daysCount: 2,
    status: 'Approved',
    notes: 'Doctor prescription provided'
  }
];

export const initialUsers: UserAccount[] = [
  {
    id: 'usr-1',
    username: 'prashant',
    displayName: 'Prashant',
    email: 'prashant@centraldispatch.bm',
    role: 'superadmin',
    status: 'Active',
    lastLogin: '2026-09-10 12:30 PM',
    createdAt: '2026-01-01'
  },
  {
    id: 'usr-2',
    username: 'superadmin',
    displayName: 'Super Admin (Default)',
    email: 'admin@centraldispatch.bm',
    role: 'superadmin',
    status: 'Active',
    lastLogin: '2026-09-09 09:15 AM',
    createdAt: '2026-01-01'
  },
  {
    id: 'usr-3',
    username: 'alesia',
    displayName: 'Alesia Brangman',
    email: 'alesia.b@centraldispatch.bm',
    role: 'admin',
    status: 'Active',
    lastLogin: '2026-09-08 04:45 PM',
    createdAt: '2026-02-15'
  },
  {
    id: 'usr-4',
    username: 'staff_assistant',
    displayName: 'Staff Assistant',
    email: 'assistant@centraldispatch.bm',
    role: 'staff',
    status: 'Active',
    lastLogin: '2026-09-07 08:30 AM',
    createdAt: '2026-03-01'
  }
];

export const initialAuditLogs: AuditLogItem[] = [
  {
    id: 'aud-1',
    action: 'PAYROLL_DRAFT_SAVED',
    module: 'Payroll',
    user: 'prashant',
    role: 'Super Admin',
    timestamp: '2026-09-10 12:00 PM',
    details: 'Saved draft for pay period Sept 3 - Sept 9, 2026'
  }
];

export const initialSchedules: EmployeeSchedule[] = [];
