(()=>{
  const DATA=window.CDL_IMPORTED_DATA||{customers:[],employees:[],generalLedger:[],meta:{}};
  const KEY='cdlAccountingV1';
  const $=id=>String(id).startsWith('[')?document.querySelector(id):document.getElementById(id), esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'BMD'}).format(Number(n)||0);
  const today=()=>new Date().toISOString().slice(0,10), uid=p=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
  const initial=()=>({version:1,customers:DATA.customers||[],employees:DATA.employees||[],invoices:[],payments:[],customLedger:[],selectedCustomerId:'',asOf:today()});
  let state=initial();
  function load(){try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved)state={...initial(),...saved}}catch(_){state=initial()} if(!state.customers.length)state.customers=DATA.customers||[];if(!state.employees.length)state.employees=DATA.employees||[];save()}
  function save(){localStorage.setItem(KEY,JSON.stringify(state))}
  function invoicePaid(id){return state.payments.filter(p=>p.invoiceId===id).reduce((s,p)=>s+Number(p.amount||0),0)}
  function invoiceBalance(i){return Math.max(0,Number(i.amount||0)-invoicePaid(i.id))}
  function invoiceStatus(i){return invoiceBalance(i)<=0.004?'Paid':'Owing'}
  function customerBalance(id){return state.invoices.filter(i=>i.customerId===id).reduce((s,i)=>s+invoiceBalance(i),0)-state.payments.filter(p=>p.customerId===id&&!p.invoiceId).reduce((s,p)=>s+Number(p.amount||0),0)}
  function openInvoices(id){return state.invoices.filter(i=>i.customerId===id&&invoiceBalance(i)>0.004)}
  function customer(id){return state.customers.find(c=>c.id===id)}
  function daysLate(due,asOf){return Math.floor((new Date(`${asOf}T12:00:00`)-new Date(`${due}T12:00:00`))/86400000)}
  function agingFor(id,asOf=state.asOf){const a={current:0,d1:0,d31:0,d61:0,d90:0,total:0};openInvoices(id).forEach(i=>{if(i.date>asOf)return;const b=invoiceBalance(i),days=daysLate(i.dueDate||i.date,asOf);a.total+=b;if(days<=0)a.current+=b;else if(days<=30)a.d1+=b;else if(days<=60)a.d31+=b;else if(days<=90)a.d61+=b;else a.d90+=b});return a}
  function allGL(){const added=[];state.invoices.forEach(i=>{const c=customer(i.customerId);added.push({id:`${i.id}_ar`,date:i.date,type:'Invoice',number:i.number,name:c?.name||'',memo:i.memo||'Customer invoice',account:'Accounts Receivable',debit:Number(i.amount),credit:0,balance:null,source:'Created in App'});added.push({id:`${i.id}_rev`,date:i.date,type:'Invoice',number:i.number,name:c?.name||'',memo:i.memo||'Customer invoice',account:'Service Income',debit:0,credit:Number(i.amount),balance:null,source:'Created in App'})});state.payments.forEach(p=>{const c=customer(p.customerId);added.push({id:`${p.id}_cash`,date:p.date,type:'Payment',number:p.reference,name:c?.name||'',memo:`${p.method||'Payment'} received`,account:'Cash / Bank',debit:Number(p.amount),credit:0,balance:null,source:'Created in App'});added.push({id:`${p.id}_ar`,date:p.date,type:'Payment',number:p.reference,name:c?.name||'',memo:'Applied to customer balance',account:'Accounts Receivable',debit:0,credit:Number(p.amount),balance:null,source:'Created in App'})});return [...(DATA.generalLedger||[]),...added,...state.customLedger].sort((a,b)=>String(b.date).localeCompare(String(a.date)))}
  function showToast(msg){const t=$('toast');if(t){t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}else alert(msg)}
  function options(selected='',onlyOpen=false){return state.customers.filter(c=>(!onlyOpen||openInvoices(c.id).length)&&(c.status!=='Inactive'||c.id===selected)).map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${esc(c.name)}${c.status==='Inactive'?' [Inactive]':''}${customerBalance(c.id)?` (${money(customerBalance(c.id))})`:''}</option>`).join('')}
  function renderDashboard(){const totalAR=state.customers.reduce((s,c)=>s+Math.max(0,customerBalance(c.id)),0),overdue=state.customers.reduce((s,c)=>{const a=agingFor(c.id);return s+a.d1+a.d31+a.d61+a.d90},0),received=state.payments.reduce((s,p)=>s+Number(p.amount||0),0);if($('acctCustomerCount')){$('acctCustomerCount').textContent=state.customers.length.toLocaleString();$('acctOpenInvoices').textContent=state.invoices.filter(i=>invoiceBalance(i)>0.004).length.toLocaleString();$('acctReceivable').textContent=money(totalAR);$('acctOverdue').textContent=money(overdue);$('acctReceived').textContent=money(received);$('acctImportSummary').textContent=`${DATA.meta?.customerRecords||state.customers.length} customers • ${DATA.meta?.employeeRecords||state.employees.length} employees • ${(DATA.meta?.ledgerTransactions||0).toLocaleString()} imported ledger transactions`}renderDashboardCustomers();}
  function renderDashboardCustomers(){if(!$('dashboardCustomerRows'))return;const q=($('dashboardCustomerSearch').value||'').trim().toLowerCase();const rows=state.customers.filter(c=>[c.name,c.customerName,c.phone,c.email,c.billingAddress,c.shippingAddress,...(c.aliases||[])].join(' ').toLowerCase().includes(q));$('dashboardCustomerCount').textContent=`${rows.length.toLocaleString()} customer${rows.length===1?'':'s'}`;$('dashboardCustomerRows').innerHTML=rows.map(c=>`<tr><td><button class="customer-link" data-dashboard-customer="${c.id}">${esc(c.name)}</button><div class="role">${esc((c.aliases||[]).slice(0,2).join(' • '))}</div></td><td>${esc(c.phone||'—')}</td><td>${esc(c.email||'—')}</td><td>${esc(c.billingAddress||'—')}</td><td>${esc(c.status||'Active')}</td><td class="money">${money(customerBalance(c.id))}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No customers match this search.</td></tr>';document.querySelectorAll('[data-dashboard-customer]').forEach(b=>b.onclick=()=>{state.selectedCustomerId=b.dataset.dashboardCustomer;save();document.querySelector('[data-view="customersView"]').click()})}
  function renderCustomers(){const q=($('customerSearch').value||'').toLowerCase(),status=$('customerStatusFilter')?.value||'',rows=state.customers.filter(c=>(!status||(c.status||'Active')===status)&&[c.name,c.customerName,c.phone,c.email,c.billingAddress,c.shippingAddress,c.notes,...(c.aliases||[])].join(' ').toLowerCase().includes(q));$('customerCountLabel').textContent=`${rows.length.toLocaleString()} shown`; $('customerRows').innerHTML=rows.map(c=>`<tr><td><button class="customer-link" data-customer="${c.id}">${esc(c.name)}</button><div class="role">${esc((c.aliases||[]).slice(0,2).join(' • '))}</div></td><td>${esc(c.phone||'—')}</td><td>${esc(c.email||'—')}</td><td>${esc(c.billingAddress||'—')}</td><td class="customer-note-cell">${esc(c.notes||'—')}</td><td><span class="record-status ${(c.status||'Active').toLowerCase()}">${esc(c.status||'Active')}</span></td><td class="money">${money(customerBalance(c.id))}</td><td><div class="acct-actions"><button class="btn" data-edit-customer="${c.id}">Edit / Note</button><button class="btn danger" data-delete-customer="${c.id}">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="8" class="empty">No customers match this search.</td></tr>';document.querySelectorAll('[data-customer]').forEach(b=>b.onclick=()=>selectCustomerLedger(b.dataset.customer));document.querySelectorAll('[data-edit-customer]').forEach(b=>b.onclick=()=>openCustomerEditor(b.dataset.editCustomer));document.querySelectorAll('[data-delete-customer]').forEach(b=>b.onclick=()=>deleteCustomer(b.dataset.deleteCustomer))}
  function ledgerRows(id){const invoices=state.invoices.filter(i=>i.customerId===id).map(i=>({date:i.date,type:'Invoice',number:i.number,memo:i.memo||'',charge:Number(i.amount),payment:0,id:i.id}));const payments=state.payments.filter(p=>p.customerId===id).map(p=>({date:p.date,type:'Payment',number:p.reference,memo:`${p.method||'Payment'}${p.invoiceId?' • Applied to invoice':''}`,charge:0,payment:Number(p.amount),id:p.id}));return [...invoices,...payments].sort((a,b)=>a.date.localeCompare(b.date)||a.type.localeCompare(b.type))}
  function selectCustomerLedger(id){state.selectedCustomerId=id;save();renderCustomerLedger();$('customerLedgerPanel').scrollIntoView({behavior:'smooth'})}
  function renderCustomerLedger(){const c=customer(state.selectedCustomerId)||state.customers[0];if(!c){$('customerLedgerPanel').innerHTML='<div class="empty-card">No customer records are available.</div>';return}state.selectedCustomerId=c.id;save();let running=0;const rows=ledgerRows(c.id).map(r=>{running+=r.charge-r.payment;return `<tr><td>${esc(r.date)}</td><td>${r.type}</td><td>${esc(r.number)}</td><td>${esc(r.memo)}</td><td class="money">${r.charge?money(r.charge):'—'}</td><td class="money">${r.payment?money(r.payment):'—'}</td><td class="money">${money(running)}</td></tr>`}).join('');const historical=(DATA.generalLedger||[]).filter(g=>g.type==='Payment'&&g.name&&([c.name,c.customerName,...(c.aliases||[])].some(n=>n&&g.name.toLowerCase().includes(String(n).toLowerCase())))).length;$('customerLedgerPanel').innerHTML=`<div class="section-head"><div><h2>${esc(c.name)} — Customer Ledger</h2><span class="record-status ${(c.status||'Active').toLowerCase()}">${esc(c.status||'Active')}</span></div><strong>${money(customerBalance(c.id))}</strong></div><div class="ledger-actions"><button class="btn primary" data-ledger-invoice>Create Invoice</button><button class="btn" data-ledger-payment>Record Payment</button><button class="btn" data-ledger-email>Email Ledger</button><button class="btn" data-ledger-edit>Edit Customer</button></div><div class="accounting-note">${esc(c.phone||'No phone')}${c.email?' • '+esc(c.email):' • No email'} • ${historical} matching historical payment record(s) are available in the imported General Ledger.</div><div class="table-wrap"><table class="compact-table"><thead><tr><th>Date</th><th>Type</th><th>Number</th><th>Description</th><th class="money">Charge</th><th class="money">Payment</th><th class="money">Balance</th></tr></thead><tbody>${rows||'<tr><td colspan="7" class="empty">No invoices or payments recorded in this app yet.</td></tr>'}</tbody></table></div>`;$('[data-ledger-invoice]').onclick=()=>goToCustomerAction('invoicesView');$('[data-ledger-payment]').onclick=()=>goToCustomerAction('paymentsView');$('[data-ledger-email]').onclick=()=>emailCustomerLedger(c.id);$('[data-ledger-edit]').onclick=()=>openCustomerEditor(c.id)}

  function goToCustomerAction(view){save();document.querySelector(`[data-view="${view}"]`).click()}
  function ensureRecordModal(){if($('recordEditorModal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="recordEditorModal" class="modal" role="dialog" aria-modal="true"><div class="modal-card record-editor-card"><div class="modal-head"><h2 id="recordEditorTitle">Edit Record</h2><button class="close" id="closeRecordEditor" aria-label="Close">×</button></div><form id="recordEditorForm" class="accounting-form"></form></div></div>`);$('closeRecordEditor').onclick=closeRecordEditor;$('recordEditorModal').onclick=e=>{if(e.target===$('recordEditorModal'))closeRecordEditor()}}
  function closeRecordEditor(){$('recordEditorModal')?.classList.remove('open')}
  function openCustomerEditor(id=''){ensureRecordModal();const c=customer(id)||{id:'',name:'',customerName:'',phone:'',email:'',billingAddress:'',shippingAddress:'',status:'Active',notes:'',aliases:[]};$('recordEditorTitle').textContent=id?'Edit Customer':'Add Customer';$('recordEditorForm').innerHTML=`<input type="hidden" name="id" value="${esc(c.id)}"><div><label>Customer Name</label><input name="name" required value="${esc(c.name)}"></div><div><label>Customer / Company Name</label><input name="customerName" value="${esc(c.customerName||'')}"></div><div><label>Phone Number</label><input name="phone" value="${esc(c.phone||'')}"></div><div><label>Email Address</label><input name="email" type="email" value="${esc(c.email||'')}"></div><div class="wide"><label>Billing Address</label><textarea name="billingAddress">${esc(c.billingAddress||'')}</textarea></div><div class="wide"><label>Shipping / Service Address</label><textarea name="shippingAddress">${esc(c.shippingAddress||'')}</textarea></div><div><label>Status</label><select name="status"><option ${c.status!=='Inactive'?'selected':''}>Active</option><option ${c.status==='Inactive'?'selected':''}>Inactive</option></select></div><div class="wide"><label>Notes</label><textarea name="notes">${esc(c.notes||'')}</textarea></div><div class="wide editor-actions"><button class="btn" type="button" id="cancelRecordEditor">Cancel</button><button class="btn primary" type="submit">Save Customer</button></div>`;$('cancelRecordEditor').onclick=closeRecordEditor;$('recordEditorForm').onsubmit=saveCustomerRecord;$('recordEditorModal').classList.add('open')}
  function saveCustomerRecord(e){e.preventDefault();const f=new FormData(e.currentTarget),id=f.get('id'),record={id:id||uid('customer'),name:String(f.get('name')).trim(),customerName:String(f.get('customerName')).trim(),phone:String(f.get('phone')).trim(),email:String(f.get('email')).trim(),billingAddress:String(f.get('billingAddress')).trim(),shippingAddress:String(f.get('shippingAddress')).trim(),status:String(f.get('status')),notes:String(f.get('notes')).trim(),aliases:customer(id)?.aliases||[]};if(id)state.customers=state.customers.map(c=>c.id===id?{...c,...record}:c);else state.customers.push(record);state.customers.sort((a,b)=>a.name.localeCompare(b.name));state.selectedCustomerId=record.id;save();closeRecordEditor();renderCustomers();renderCustomerLedger();renderDashboard();showToast(id?'Customer updated':'Customer added')}
  function deleteCustomer(id){const c=customer(id);if(!c)return;if(state.invoices.some(i=>i.customerId===id)||state.payments.some(p=>p.customerId===id))return alert('This customer has invoices or payments. Mark the customer Inactive instead of deleting the record.');if(!confirm(`Delete ${c.name}? This cannot be undone.`))return;state.customers=state.customers.filter(x=>x.id!==id);if(state.selectedCustomerId===id)state.selectedCustomerId='';save();renderCustomers();renderCustomerLedger();renderDashboard();showToast('Customer deleted')}
  function emailCustomerLedger(id){const c=customer(id);if(!c?.email||!c.email.includes('@'))return alert('This customer does not have a valid email address. Edit the customer record first.');let running=0;const lines=ledgerRows(id).map(r=>{running+=r.charge-r.payment;return `${r.date} | ${r.type} ${r.number||''} | Charge ${money(r.charge)} | Payment ${money(r.payment)} | Balance ${money(running)}`}).join('\n')||'No invoices or payments are recorded.';const subject=`Central Dispatch Customer Ledger — ${c.name}`,body=`Good day ${c.name},\n\nPlease find your customer ledger summary below.\n\n${lines}\n\nCurrent balance: ${money(customerBalance(id))}\n\nKind regards,\nCentral Dispatch Limited / Bermuda Island Taxi\ninfo@bermudaislandtaxi.com\n+1 (441) 295-4141`;window.location.href=`mailto:${encodeURIComponent(c.email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}
  function invoiceLineHTML(item={}){const n=$('invoiceLineRows').children.length+1;return `<tr><td class="num">${n}</td><td><input class="line-service" value="${esc(item.service||'Island Taxi')}" placeholder="Island Taxi"></td><td><input class="line-description" value="${esc(item.description||'')}" placeholder="Trip, date, passenger, pickup and destination"></td><td><input class="line-quantity entry" type="number" min="0" step="1" value="${Number(item.quantity||1)}"></td><td><input class="line-rate entry" type="number" min="0" step="0.01" value="${item.rate??''}"></td><td class="line-amount money">${money(Number(item.quantity||1)*Number(item.rate||0))}</td><td><button class="btn danger remove-invoice-line" type="button">Remove</button></td></tr>`}
  function bindInvoiceLines(){document.querySelectorAll('#invoiceLineRows input').forEach(i=>i.oninput=recalculateInvoice);document.querySelectorAll('.remove-invoice-line').forEach(b=>b.onclick=()=>{if($('invoiceLineRows').children.length===1){b.closest('tr').querySelectorAll('input').forEach(i=>i.value=i.classList.contains('line-quantity')?'1':'');return recalculateInvoice()}b.closest('tr').remove();[...$('invoiceLineRows').children].forEach((r,i)=>r.firstElementChild.textContent=i+1);recalculateInvoice()})}
  function addInvoiceLine(item={}){$('invoiceLineRows').insertAdjacentHTML('beforeend',invoiceLineHTML(item));bindInvoiceLines();recalculateInvoice()}
  function invoiceItems(){return [...$('invoiceLineRows').children].map(r=>({service:r.querySelector('.line-service').value.trim()||'Island Taxi',description:r.querySelector('.line-description').value.trim(),quantity:Number(r.querySelector('.line-quantity').value||0),rate:Number(r.querySelector('.line-rate').value||0)})).filter(i=>i.description||i.rate).map(i=>({...i,amount:i.quantity*i.rate}))}
  function recalculateInvoice(){[...$('invoiceLineRows').children].forEach(r=>{r.querySelector('.line-amount').textContent=money(Number(r.querySelector('.line-quantity').value||0)*Number(r.querySelector('.line-rate').value||0))});$('invoiceAmount').textContent=money(invoiceItems().reduce((s,i)=>s+i.amount,0))}
  function setInvoiceCustomerEmail(){const c=customer($('invoiceCustomer').value);$('invoiceEmail').value=c?.email||''}
  function termsDueDate(){const map={'Due on receipt':0,'Net 7':7,'Net 15':15,'Net 30':30,'Net 60':60},d=new Date(`${$('invoiceDate').value||today()}T12:00:00`);d.setDate(d.getDate()+(map[$('invoiceTerms').value]??30));$('invoiceDue').value=d.toISOString().slice(0,10)}
  function renderInvoiceForm(){$('invoiceCustomer').innerHTML='<option value="">Select customer</option>'+options();if(state.selectedCustomerId)$('invoiceCustomer').value=state.selectedCustomerId;$('invoiceDate').value||=today();if(!$('invoiceDue').value)termsDueDate();setInvoiceCustomerEmail();if(!$('invoiceLineRows').children.length){for(let i=0;i<5;i++)addInvoiceLine()}renderInvoiceHistory()}
  function renderInvoiceHistory(){const rows=[...state.invoices].sort((a,b)=>b.date.localeCompare(a.date));$('invoiceHistoryRows').innerHTML=rows.map(i=>{const c=customer(i.customerId),status=invoiceStatus(i);return `<tr><td>${esc(i.date)}</td><td><strong>${esc(i.number)}</strong></td><td>${esc(c?.name||'Unknown')}</td><td><span class="invoice-status ${status.toLowerCase()}">${status}</span></td><td class="money">${money(i.amount)}</td><td class="money">${money(invoiceBalance(i))}</td><td><div class="acct-actions"><button class="btn" data-preview-invoice="${i.id}">Preview / Print</button><button class="btn primary" data-email-invoice="${i.id}">Email ${status==='Paid'?'Paid Invoice':'Invoice'}</button><button class="btn danger" data-delete-invoice="${i.id}">Delete</button></div></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">No invoices saved yet.</td></tr>';document.querySelectorAll('[data-preview-invoice]').forEach(b=>b.onclick=()=>showInvoice(b.dataset.previewInvoice));document.querySelectorAll('[data-email-invoice]').forEach(b=>b.onclick=()=>emailInvoice(b.dataset.emailInvoice));document.querySelectorAll('[data-delete-invoice]').forEach(b=>b.onclick=()=>deleteInvoice(b.dataset.deleteInvoice))}
  function invoicePreviewHTML(i){const c=customer(i.customerId)||{},items=i.items?.length?i.items:[{service:'Service',description:i.memo||'Customer invoice',quantity:1,rate:Number(i.amount),amount:Number(i.amount)}],paid=invoicePaid(i.id),balance=invoiceBalance(i);return `<article class="invoice-preview"><div class="invoice-preview-head"><div><h1>INVOICE</h1><strong>Central Dispatch Limited / Bermuda Island Taxi</strong><div>18 Boulden Circle<br>New Castle, DE 19720-3494</div></div><div><strong>info@bermudaislandtaxi.com</strong><br>+1 (441) 295-4141</div></div><div class="invoice-preview-addresses"><div><strong>Bill to</strong><br>${esc(c.name||'')}<br>${esc(c.billingAddress||'')}<br>${esc(c.email||'')}</div><div><strong>Ship to / Service customer</strong><br>${esc(c.name||'')}<br>${esc(c.shippingAddress||c.billingAddress||'')}</div></div><div class="invoice-preview-meta"><div><strong>Invoice No.</strong><br>${esc(i.number)}</div><div><strong>Terms</strong><br>${esc(i.terms||'Due on receipt')}</div><div><strong>Invoice Date</strong><br>${esc(i.date)}</div><div><strong>Due Date</strong><br>${esc(i.dueDate)}</div></div><table><thead><tr><th>#</th><th>Product or Service</th><th>Description</th><th class="money">Qty</th><th class="money">Rate</th><th class="money">Amount</th></tr></thead><tbody>${items.map((x,n)=>`<tr><td>${n+1}</td><td>${esc(x.service)}</td><td>${esc(x.description)}</td><td class="money">${Number(x.quantity).toFixed(2)}</td><td class="money">${money(x.rate)}</td><td class="money">${money(x.amount)}</td></tr>`).join('')}</tbody></table><div class="invoice-preview-total"><div class="total"><span>Total</span><strong>${money(i.amount)}</strong></div><div><span>Payment</span><span>${money(paid)}</span></div><div class="total"><span>Balance Due</span><strong>${money(balance)}</strong></div></div>${i.memo?`<p><strong>Message:</strong> ${esc(i.memo)}</p>`:''}</article>`}
  function ensureInvoiceModal(){if($('invoicePreviewModal'))return;document.body.insertAdjacentHTML('beforeend','<div id="invoicePreviewModal" class="modal" role="dialog" aria-modal="true"><div class="modal-card"><div class="modal-head"><h2>Customer Invoice</h2><button class="close" id="closeInvoicePreview" aria-label="Close">×</button></div><div class="invoice-modal-actions"><button class="btn primary" id="emailPreviewInvoice">Email Invoice</button><button class="btn" id="printPreviewInvoice">Print / Save PDF</button></div><div id="invoicePreviewBody"></div></div></div>');$('closeInvoicePreview').onclick=()=>$('invoicePreviewModal').classList.remove('open');$('invoicePreviewModal').onclick=e=>{if(e.target===$('invoicePreviewModal'))e.currentTarget.classList.remove('open')}}
  function showInvoice(id){ensureInvoiceModal();const i=state.invoices.find(x=>x.id===id);if(!i)return;$('invoicePreviewBody').innerHTML=invoicePreviewHTML(i);$('emailPreviewInvoice').onclick=()=>emailInvoice(id);$('printPreviewInvoice').onclick=()=>printInvoice(id);$('invoicePreviewModal').classList.add('open')}
  function printInvoice(id){const i=state.invoices.find(x=>x.id===id);if(!i)return;const w=window.open('','_blank');w.document.write(`<html><head><title>Invoice ${esc(i.number)}</title><style>body{font-family:Arial;padding:28px;color:#172235}table{border-collapse:collapse;width:100%}th,td{border-bottom:1px solid #ccd6df;padding:9px;text-align:left}.money{text-align:right}.invoice-preview-head,.invoice-preview-addresses,.invoice-preview-meta{display:flex;justify-content:space-between;gap:20px;margin:16px 0}.invoice-preview-total{margin-left:auto;width:350px}.invoice-preview-total div{display:flex;justify-content:space-between;padding:8px;border-bottom:1px solid #ddd}h1{color:#86b51b}</style></head><body>${invoicePreviewHTML(i)}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),200)}
  function emailInvoice(id){const i=state.invoices.find(x=>x.id===id),c=customer(i?.customerId);if(!i||!c)return;if(!c.email||!c.email.includes('@'))return alert('This customer does not have a valid email address. Add an email to the customer record first.');const items=(i.items||[]).map((x,n)=>`${n+1}. ${x.service} — ${x.description} | Qty ${x.quantity} × ${money(x.rate)} = ${money(x.amount)}`).join('\n'),status=invoiceStatus(i),paid=status==='Paid',subject=`Central Dispatch Invoice ${i.number} — ${paid?'Paid in Full':'Amount Due'}`,body=`Good day ${c.name},\n\n${paid?'Thank you for your payment. This invoice is paid in full.':'Please find the amount currently owing on your invoice below.'}\n\nInvoice: ${i.number}\nInvoice date: ${i.date}\nDue date: ${i.dueDate}\nTerms: ${i.terms||'Due on receipt'}\nStatus: ${paid?'PAID IN FULL':'OWING'}\n\n${items}\n\nInvoice total: ${money(i.amount)}\nPayments received: ${money(invoicePaid(i.id))}\nBalance due: ${money(invoiceBalance(i))}\n\n${i.memo||'Thank you for your business.'}\n\nKind regards,\nCentral Dispatch Limited / Bermuda Island Taxi\ninfo@bermudaislandtaxi.com\n+1 (441) 295-4141`;window.location.href=`mailto:${encodeURIComponent(c.email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}
  function deleteInvoice(id){if(state.payments.some(p=>p.invoiceId===id))return alert('This invoice has a payment applied and cannot be deleted.');if(!confirm('Delete this invoice?'))return;state.invoices=state.invoices.filter(i=>i.id!==id);save();renderInvoiceHistory();renderDashboard();showToast('Invoice deleted')}
  function renderPaymentForm(){const current=$('paymentCustomer').value||state.selectedCustomerId;$('paymentCustomer').innerHTML='<option value="">Select customer</option>'+options(current);$('paymentDate').value||=today();renderPaymentInvoices()}
  function renderPaymentInvoices(){const id=$('paymentCustomer').value;$('paymentInvoice').innerHTML='<option value="">Unapplied / customer credit</option>'+openInvoices(id).map(i=>`<option value="${i.id}">${esc(i.number)} • ${esc(i.dueDate)} • ${money(invoiceBalance(i))}</option>`).join('')}
  function renderAging(){state.asOf=$('agingAsOf').value||today();save();const rows=state.customers.map(c=>({c,a:agingFor(c.id)})).filter(x=>x.a.total>0.004).sort((a,b)=>b.a.total-a.a.total);const total=rows.reduce((o,x)=>{Object.keys(o).forEach(k=>o[k]+=x.a[k]);return o},{current:0,d1:0,d31:0,d61:0,d90:0,total:0});$('agingRows').innerHTML=rows.map(({c,a})=>`<tr><td><button class="customer-link" data-aging-customer="${c.id}">${esc(c.name)}</button></td><td class="money aging-current">${money(a.current)}</td><td class="money aging-overdue">${money(a.d1)}</td><td class="money aging-overdue">${money(a.d31)}</td><td class="money aging-overdue">${money(a.d61)}</td><td class="money aging-overdue">${money(a.d90)}</td><td class="money"><strong>${money(a.total)}</strong></td></tr>`).join('')+`<tr class="acct-summary-row"><td>TOTAL</td><td class="money">${money(total.current)}</td><td class="money">${money(total.d1)}</td><td class="money">${money(total.d31)}</td><td class="money">${money(total.d61)}</td><td class="money">${money(total.d90)}</td><td class="money">${money(total.total)}</td></tr>`;document.querySelectorAll('[data-aging-customer]').forEach(b=>b.onclick=()=>{state.selectedCustomerId=b.dataset.agingCustomer;save();document.querySelector('[data-view="customersView"]').click();setTimeout(()=>renderCustomerLedger(),0)})}
  function renderGL(){const q=($('glSearch').value||'').toLowerCase(),year=$('glYear').value,type=$('glType').value;let rows=allGL().filter(g=>(!year||String(g.date).startsWith(year))&&(!type||g.type===type)&&(!q||[g.name,g.memo,g.account,g.number,g.type].join(' ').toLowerCase().includes(q)));$('glCountLabel').textContent=`${rows.length.toLocaleString()} transactions`;const debit=rows.reduce((s,r)=>s+Number(r.debit||0),0),credit=rows.reduce((s,r)=>s+Number(r.credit||0),0);$('glDebitTotal').textContent=money(debit);$('glCreditTotal').textContent=money(credit);$('glRows').innerHTML=rows.slice(0,700).map(g=>`<tr><td>${esc(g.date)}</td><td>${esc(g.type)}</td><td>${esc(g.number)}</td><td>${esc(g.name)}</td><td>${esc(g.memo)}</td><td>${esc(g.account)}</td><td class="money">${g.debit?money(g.debit):'—'}</td><td class="money">${g.credit?money(g.credit):'—'}</td><td><span class="source-pill">${esc(g.source||'Imported')}</span></td></tr>`).join('')||'<tr><td colspan="9" class="empty">No ledger entries match the filters.</td></tr>'}
  function renderEmployees(){$('importedEmployeeRows').innerHTML=state.employees.map(e=>`<tr><td><strong>${esc(e.name)}</strong></td><td>${esc(e.phone||'—')}</td><td>${esc(e.email||'—')}</td><td>${esc(e.address||'—')}</td><td><span class="record-status ${(e.status||'Active').toLowerCase()}">${esc(e.status||'Active')}</span></td><td><div class="acct-actions"><button class="btn" data-edit-employee="${e.id}">Edit</button><button class="btn danger" data-delete-employee="${e.id}">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No employee records are available.</td></tr>';document.querySelectorAll('[data-edit-employee]').forEach(b=>b.onclick=()=>openEmployeeEditor(b.dataset.editEmployee));document.querySelectorAll('[data-delete-employee]').forEach(b=>b.onclick=()=>deleteEmployee(b.dataset.deleteEmployee))}
  function employee(id){return state.employees.find(e=>e.id===id)}
  function openEmployeeEditor(id=''){ensureRecordModal();const e=employee(id)||{id:'',name:'',phone:'',email:'',address:'',status:'Active'};$('recordEditorTitle').textContent=id?'Edit Employee':'Add Employee';$('recordEditorForm').innerHTML=`<input type="hidden" name="id" value="${esc(e.id)}"><div><label>Employee Name</label><input name="name" required value="${esc(e.name)}"></div><div><label>Status</label><select name="status"><option ${e.status!=='Inactive'?'selected':''}>Active</option><option ${e.status==='Inactive'?'selected':''}>Inactive</option></select></div><div><label>Phone Number</label><input name="phone" value="${esc(e.phone||'')}"></div><div><label>Email Address</label><input name="email" type="email" value="${esc(e.email||'')}"></div><div class="wide"><label>Address</label><textarea name="address">${esc(e.address||'')}</textarea></div><div class="wide editor-actions"><button class="btn" type="button" id="cancelRecordEditor">Cancel</button><button class="btn primary" type="submit">Save Employee</button></div>`;$('cancelRecordEditor').onclick=closeRecordEditor;$('recordEditorForm').onsubmit=saveEmployeeRecord;$('recordEditorModal').classList.add('open')}
  function saveEmployeeRecord(e){e.preventDefault();const f=new FormData(e.currentTarget),id=f.get('id'),record={id:id||uid('employee'),name:String(f.get('name')).trim(),phone:String(f.get('phone')).trim(),email:String(f.get('email')).trim(),address:String(f.get('address')).trim(),status:String(f.get('status'))};if(id)state.employees=state.employees.map(x=>x.id===id?{...x,...record}:x);else state.employees.push(record);state.employees.sort((a,b)=>a.name.localeCompare(b.name));save();closeRecordEditor();renderEmployees();renderDashboard();showToast(id?'Employee updated':'Employee added')}
  function deleteEmployee(id){const e=employee(id);if(!e)return;if(!confirm(`Delete ${e.name}? This removes the employee contact record from this screen.`))return;state.employees=state.employees.filter(x=>x.id!==id);save();renderEmployees();renderDashboard();showToast('Employee deleted')}
  function renderCurrent(){const id=document.querySelector('.view:not([hidden])')?.id;if(id==='dashboardView'||id==='accountingView')renderDashboard();if(id==='customersView'){renderCustomers();renderCustomerLedger()}if(id==='invoicesView')renderInvoiceForm();if(id==='paymentsView')renderPaymentForm();if(id==='agingView')renderAging();if(id==='generalLedgerView')renderGL();if(id==='importedEmployeesView')renderEmployees()}
  function exportTable(name,title,headers,rows){const html=`<html><head><meta charset="utf-8"><style>body{font-family:Arial}table{border-collapse:collapse}th,td{border:1px solid #bbb;padding:8px}th{background:#12345b;color:white}</style></head><body><h1>${esc(title)}</h1><table><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</table></body></html>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([html],{type:'application/vnd.ms-excel'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  load();
  document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setTimeout(renderCurrent,0)));
  $('customerSearch').oninput=renderCustomers;$('customerStatusFilter').onchange=renderCustomers;$('dashboardCustomerSearch').oninput=renderDashboardCustomers;$('addCustomer').onclick=()=>openCustomerEditor();$('addEmployee').onclick=()=>openEmployeeEditor();
  $('addInvoiceLine').onclick=()=>addInvoiceLine();$('invoiceCustomer').onchange=setInvoiceCustomerEmail;$('invoiceDate').onchange=termsDueDate;$('invoiceTerms').onchange=termsDueDate;
  $('invoiceForm').onsubmit=e=>{e.preventDefault();const customerId=$('invoiceCustomer').value,items=invoiceItems(),amount=items.reduce((s,i)=>s+i.amount,0);if(!customerId)return alert('Please select a customer.');if(!items.length||amount<=0)return alert('Add at least one invoice line with a description, quantity, and rate.');const number=$('invoiceNumber').value.trim()||`INV-${String(state.invoices.length+1).padStart(4,'0')}`,invoice={id:uid('inv'),customerId,number,date:$('invoiceDate').value,dueDate:$('invoiceDue').value||$('invoiceDate').value,terms:$('invoiceTerms').value,items,amount,memo:$('invoiceMemo').value.trim(),createdAt:new Date().toISOString()};state.invoices.push(invoice);state.selectedCustomerId=customerId;save();showInvoice(invoice.id);e.target.reset();$('invoiceLineRows').innerHTML='';renderInvoiceForm();renderDashboard();showToast('Invoice saved, previewed, and posted to the ledger')};
  $('paymentCustomer').onchange=renderPaymentInvoices;
  $('paymentForm').onsubmit=e=>{e.preventDefault();const customerId=$('paymentCustomer').value,amount=Number($('paymentAmount').value),invoiceId=$('paymentInvoice').value;if(!customerId||!amount||amount<=0)return alert('Select a customer and enter a payment amount greater than zero.');if(invoiceId&&amount>invoiceBalance(state.invoices.find(i=>i.id===invoiceId))+0.005&&!confirm('This payment is greater than the selected invoice balance. Record it anyway?'))return;state.payments.push({id:uid('pay'),customerId,invoiceId,date:$('paymentDate').value,amount,method:$('paymentMethod').value,reference:$('paymentReference').value.trim(),note:$('paymentNote').value.trim(),createdAt:new Date().toISOString()});state.selectedCustomerId=customerId;save();e.target.reset();renderPaymentForm();renderDashboard();showToast('Payment recorded and posted to the ledger')};
  $('agingAsOf').value=state.asOf||today();$('agingAsOf').onchange=renderAging;$('glSearch').oninput=renderGL;$('glYear').onchange=renderGL;$('glType').onchange=renderGL;
  $('exportCustomers').onclick=()=>exportTable('CDL-Customers.xls','Central Dispatch Customers',['Customer','Phone','Email','Billing Address','Status','Balance'],state.customers.map(c=>[c.name,c.phone,c.email,c.billingAddress,c.status,money(customerBalance(c.id))]));
  $('exportAging').onclick=()=>exportTable('CDL-Accounts-Receivable-Aging.xls',`Accounts Receivable Aging as of ${state.asOf}`,['Customer','Current','1-30','31-60','61-90','90+','Total'],state.customers.map(c=>({c,a:agingFor(c.id)})).filter(x=>x.a.total>0).map(x=>[x.c.name,money(x.a.current),money(x.a.d1),money(x.a.d31),money(x.a.d61),money(x.a.d90),money(x.a.total)]));
  $('exportGL').onclick=()=>exportTable('CDL-General-Ledger.xls','Central Dispatch General Ledger',['Date','Type','Number','Name','Memo','Account','Debit','Credit','Source'],allGL().map(g=>[g.date,g.type,g.number,g.name,g.memo,g.account,g.debit||'',g.credit||'',g.source]));
  $('fullBackup').onclick=()=>{save();const data={format:'CDL Complete App Backup',createdAt:new Date().toISOString(),localStorage:Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith('cdl')).map(k=>[k,localStorage.getItem(k)]))};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`CDL-Complete-Backup-${today()}.json`;a.click();showToast('Complete app backup downloaded')};
  $('fullRestore').onclick=()=>$('fullRestoreFile').click();$('fullRestoreFile').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!data.localStorage)throw new Error();if(!confirm('Restore this complete backup and replace the current locally saved app data?'))return;Object.entries(data.localStorage).forEach(([k,v])=>localStorage.setItem(k,v));location.reload()}catch(_){alert('This complete backup could not be restored.')}};
  renderCurrent();
})();
